***
```{r Period-flow-{{period.name}}, results='asis'}
cat("#### {{period.name}}")
text.plot=11
figure.width = 9
figure.height = 4
```

```{r flow-plots-{{period.name}}, echo=FALSE, message=FALSE, results='asis', warning=FALSE, error=FALSE, fig.width=figure.width, fig.height=figure.height, fig.keep='all'}

ggplot(zonal.flows[Period == '{{period.name}}', ], aes(x=time, y=-value/1000, color=name, group=name))+
      geom_line(size=1.3)+
      geom_hline(yintercept=0, color="black", size=0.3)+
        scale_x_datetime(breaks = date_breaks(width = "1 day"), labels = date_format("%b %d\n%I %p"), expand = c(0, 0))+
        scale_color_manual("", values = scen.pal)+
            labs(y="Flow (GW)", x = '')+
            theme(legend.key = element_rect(NULL),
                  legend.text = element_text(size=text.plot),
                  text=element_text(size=text.plot),
                  strip.text=element_text(face="bold", size=rel(1)),
                  axis.text=element_text(face=2, size=text.plot/1),
                  axis.title=element_text(size=text.plot, face=2.3),
                  # legend.position=c(0.80, 0.12),
                  panel.spacing = unit(0.35, "lines"))+
            facet_wrap(~Period, scales = 'free_x', nrow=4)
```



  
  