
```{r key-period-line-flow-{{period.name}}, results='asis', include=TRUE}
p.name = '{{period.name}}' # Set key period name
cat("### ", p.name) # Print period name above plot
text.plot=11 # Set plot text size
figure.width = 9
figure.height = 6
```

```{r key-period-line-flow-plots-{{period.name}}, fig.width=figure.width, fig.height=figure.height, include=TRUE}

ggplot(plot.flows[Period==p.name, ], aes(time, value/1000, group=name, color=name))+
      geom_line(size = 1.2)+
      geom_hline(yintercept=0, color="black", size=0.3)+
      labs(y="Flow (GW)", x=NULL)+
      scale_color_manual("", values = scen.pal)+
      scale_x_datetime(breaks = date_breaks(width = "1 day"), labels = date_format("%b %d\n%I %p"), expand = c(0, 0))+
              theme(legend.key = element_rect(NULL),
                  legend.text = element_text(size=text.plot),
                  text=element_text(size=text.plot),
                  strip.text=element_text(face="bold", size=rel(1)),
                  axis.text=element_text(face=2, size=text.plot/1),
                  axis.title=element_text(size=text.plot, face=2.3),
                  # legend.position=c(0.80, 0.12),
                  panel.spacing = unit(0.35, "lines"),
                  aspect.ratio = 0.5)    
  
```



  
  