setwd(dirname(parent.frame(2)$ofile))
pacman::p_load(data.table)
SourceData = normalizePath(file.path('../../../SourceData/'))
extra_input.dir = normalizePath(file.path('./1-parse-matpower/extra_inputs/'))
output.dir = normalizePath(file.path('./1-parse-matpower/outputs/'))
file.remove(output.dir)
file.copy(extra_input.dir,output.dir)
source('1-parse-matpower/parse_rts.R')
setwd('2-create-excel')
source('run_PSSE2PLEXOS.R')
setwd('..')
