
```{r DA-RT-scen-region-{{region.name}}-{{period.name}}, results='asis', include=TRUE}
r.name = '{{region.name}}' # Assign region name
p.name = '{{period.name}}' # Assign period name
cat("### ", p.name, ': ', r.name) # Print period and region name above the plot
text.plot=14 # Plot text size.
figure.width = max(5*plot.data.all[Type %in% da.rt.types & Region==r.name & Period==p.name, length(unique(scenario))], 5)
figure.height = max(2*plot.data.all[Type %in% da.rt.types & Region==r.name & Period==p.name, length(unique(Type))], 2)
```

```{r DA-RT-scen-plot-region-{{region.name}}-{{period.name}}, fig.width=figure.width, fig.height=figure.height, include=TRUE}
# Check to make sure this region shouldn't be ignored.
if ( !r.name %in% ignore.regions ) {
  
  # Pull out only the data for the generation types specified in the input file and the current region and period.
  plot.data = plot.data.all[Type %in% da.rt.types & Region==r.name & Period==p.name, 
                            .(value = sum(value)), 
                            by=.(scenario, Region, time, Type, Period, data)]
  
  # Check that there is actually generation data to plot, otherwise don't make a plot.
  if ( plot.data[, sum(value)]>0 ) {

    p = commitment_dispatch_plot(plot.data)
    print(p+facet_grid(Type~scenario, scales="free_y")+theme(panel.spacing.x = unit(2,'lines')))
    
    
  }
}
```
